{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafka-rest-json-adaper-helm-chart.serviceAccountName" . }}
  labels:
{{ include "kafka-rest-json-adaper-helm-chart.labels" . | indent 4 }}
{{- end -}}
